server:
  port: 2333

spring:
  application:
    name: account-service

eureka:
  client:
    fetch-registry: true
  instance:
    lease-expiration-duration-in-seconds: 4
    lease-renewal-interval-in-seconds: 2
